### ISSUE TITLE
Mark question as a duplicate of a developerworks question

### ISSUE THREAD

**Issue by isc-rsingh** [ibm-cds-labs/sodashboard#20] opened 2017-05-15 16:24 UTC

**Comment by ptitzler** [comment] 2017-05-15 16:49
To keep this IBM-agostic we should probably embed this information in the notes for now.

**Comment by vabarbosa** [comment] 2017-05-16 16:11
not necessarily just developerworks question, couldnt it also be a duplicate of an existing stackoverflow question?

**Comment by isc-rsingh** [comment] 2017-05-18 15:19
Duplicate of an SO question should be noted in the SO question itself. But there are other places questions are asked and answered, like Quora, so one could argue the feature is IBM-agnostic.

**Comment by lornajane** [comment] 2017-06-06 16:23
Agreed to use the notes field for now.

**Closed as completed by lornajane** 2017-06-06 16:23 UTC
